services:
#####micro-service clients
  contentServiceClient:
    class: FastMicroKernel\Components\ServiceClientsFactory
    factory: ['FastMicroKernel\Components\ServiceClientsFactory', 'getServiceClient']
    arguments:
      - '@=constant("CONTENT_SERVICE_CLIENT_TRANSPORT")'
      - /content

#####micro-service request builder
  serviceRequestBuilder:
    class: FastMicroKernel\Components\ServiceRequestBuilder

##### application factories
  applicationDtoFactory:
    class: Target\Factories\DtoFactory

##### domain delivery context factories
  domainDeliveryDtoFactory:
    class: Target\Domain\DeliveryContext\Factories\DtoFactory
  domainDeliveryCollectionsFactory:
    class: Target\Domain\DeliveryContext\Factories\CollectionsFactory
  domainDeliveryEntitiesFactory:
    class: Target\Domain\DeliveryContext\Factories\EntitiesFactory
    arguments:
      - '@domainDeliveryCollectionsFactory'
      - '@domainDeliveryValueObjectsFactory'
  domainDeliveryValueObjectsFactory:
    class: Target\Domain\DeliveryContext\Factories\ValueObjectsFactory

##### domain delivery context services
  domainDeliveryTargetService:
    class: Target\Domain\DeliveryContext\Services\TargetService
    arguments:
      - '@domainDeliveryDtoFactory'
      - '@domainDeliveryCollectionsFactory'
      - '@domainDeliveryEntitiesFactory'
      - '@domainDeliveryValueObjectsFactory'
#      - '@contentServiceClient'
#      - '@serviceRequestBuilder'